#Item 1
{
	:@id => 1,
	:@name => "une flamberge en aluminium",
	:@type => :arme,
	:@weight => 1,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [:main_gauche, :main_droite],
	:@desc => "Cette épée est constituée d'une lame fine et légère en aluminium.",
	:@stats => {:arme=>:épée, :puissance=>20},
	:@power => {},
	:@required => {},
	:@value => 0,
},

#Item 2
{
	:@id => 2,
	:@name => "un petit cèpe",
	:@type => :nourriture,
	:@weight => 1,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [],
	:@desc => "C'est un champignon appétissant.",
	:@stats => {:rassasiment=>240},
	:@power => {},
	:@required => {},
	:@value => 20,
},

#Item 3
{
	:@id => 3,
	:@name => "une pièce d'or",
	:@type => :money,
	:@weight => 0,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [],
	:@desc => "Ces pièces sont très utilisées dans le commerce.",
	:@stats => {},
	:@power => {},
	:@required => {},
	:@value => 1,
},

#Item 4
{
	:@id => 4,
	:@name => "une vesse-de-loup",
	:@type => :nourriture,
	:@weight => 1,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [],
	:@desc => "Les vesses-de-loup sont des champignons très répandus dans les prés et les bois, facilement reconnaissables à leur couleur blanche ou grisâtre, et au fait que lorsqu'ils sont vieux ils se transforment en sacs remplis d'une poussière brune, véritables petits volcans quand on appuie dessus.",
	:@stats => {:rassasiment=>240},
	:@power => {},
	:@required => {},
	:@value => 10,
},

#Item 5
{
	:@id => 5,
	:@name => "un cortinaire violet",
	:@type => :nourriture,
	:@weight => 1,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [],
	:@desc => "Un champignon assez rare, mais comestible, construit par des lames violettes ventrues, espacées et épaisses, poudrées de brun rouille avec l'âge sous un châpeau cônique puis étalé avec un mamelon obtus, charnu violet foncé. Le tout disposé sur un pied pouvant atteindre 15cm, s'épaississant jusqu'à la base du pied. Il présente des traces fugaces de cortine bleue.",
	:@stats => {:rassasiment=>600},
	:@power => {},
	:@required => {},
	:@value => 100,
},

#Item 6
{
	:@id => 6,
	:@name => "un morceau de gelée bleue",
	:@type => :nourriture,
	:@weight => 1,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [],
	:@desc => "C'est un petit morceau de gelée à manger, d'une couleur bleue et translucide.",
	:@stats => {},
	:@power => {:eat=>[:gain_de_vie, 50, 1000]},
	:@required => {},
	:@value => 1,
},

#Item 7
{
	:@id => 7,
	:@name => "un plastron en aluminium",
	:@type => :armure,
	:@weight => 10,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [:torse],
	:@desc => "Ce plastron en aluminium est fabriqué par Adel le forgeron pour les élèves de l'académie de l'île de Sifnos.",
	:@stats => {:armure=>5},
	:@power => {},
	:@required => {},
	:@value => 0,
},

#Item 8
{
	:@id => 8,
	:@name => "une lettre de Sifnos",
	:@type => :livre,
	:@weight => 1,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [],
	:@desc => "Cette lettre provenant de la grand école Sifnos vous est destinée. Le papier est doux et légèrement brun.",
	:@stats => {},
	:@power => {},
	:@required => {},
	:@value => 0,
},

#Item 9
{
	:@id => 9,
	:@name => "un morceau de serpent grillé",
	:@type => :nourriture,
	:@weight => 2,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [],
	:@desc => "C'est de la viande de serpent à sonnette, grillée à la broche.",
	:@stats => {:rassasiment=>500},
	:@power => {},
	:@required => {},
	:@value => 50,
},

#Item 10
{
	:@id => 10,
	:@name => "une poignée de riz brun",
	:@type => :nourriture,
	:@weight => 1,
	:@fixed => false,
	:@implantation => "% est posé là",
	:@wearon => [],
	:@desc => "Une poignée de riz sauvage, c'est déjà ça !",
	:@stats => {:rassasiment=>200},
	:@power => {},
	:@required => {},
	:@value => 10,
},

#Item 11
{
	:@id => 11,
	:@name => "une note d'introduction",
	:@type => :livre,
	:@weight => 1,
	:@fixed => true,
	:@implantation => "% (tapez <b><i>read note</b></i> pour la lire) est posée sur votre table de nuit",
	:@wearon => [],
	:@desc => "C'est une note d'introduction au jeu écrite sur du papier fin.",
	:@stats => {},
	:@power => {},
	:@required => {},
	:@value => 0,
},

#Item 12
{
	:@id => 12,
	:@name => "un bâton d'ébène verni",
	:@type => :arme,
	:@weight => 5,
	:@fixed => false,
	:@implantation => "% lévite ici",
	:@wearon => [:main_gauche, :main_droite],
	:@desc => "C'est un bâton d'ébène assez droit protégé par du vernis. Un serpentin d'énergie grise tournoie autours et semble repousser tout corps étranger rendant cette arme dure à maîtriser.",
	:@stats => {:arme=>:nécromancie, :puissance=>120},
	:@power => {},
	:@required => {:level=>40},
	:@value => 15000,
},

