#Heroe 1
{
	:@id => 1,
	:@name => "Arsenic",
	:@password => "37eff4bfa7d88a6e75c8804ecff8659b",
	:@authlevel => 1,
	:@desc => {:sex=>1, :taille=>1, :haircolor=>1, :hairlength=>1, :eyecolor=>1},
	:@room => 4,
	:@xp => 6949,
	:@level => 12,
	:@hp => 144,
	:@maxhp => 144,
	:@mp => 467,
	:@maxmp => 1086,
	:@str => 8,
	:@con => 14,
	:@wis => 11,
	:@dex => 20,
	:@armor => -5,
	:@ambidexterity => 1,
	:@skin => "Mage09",
	:@avatar => "pretre4",
	:@spell => {1=>72, 2=>100, 3=>50, 4=>33},
	:@inv => {8=>5, 9=>12, 2=>4, 1=>13, 10=>17, 7=>2, 5=>10, 12=>11},
	:@equip => {:main_gauche=>12},
	:@shortcut => [["Armure 1", "Sac 1", "Lettre 2", "Lettre 3", "Weapon 4", "Plume 1", "Skill 7", "Masque 1", "Joyaux 11", "Skill 6"], ["equipement", "inventory", "option", "spells;test", "skills", "redit", "score", "who", "team", "aide"]],
	:@hunger => -11700,
},

#Heroe 2
{
	:@id => 2,
	:@name => "Maxime",
	:@password => "b238c13e822536cad3ac57a2280fbf45",
	:@authlevel => 1,
	:@desc => {:sex=>1, :taille=>4, :haircolor=>5, :hairlength=>2, :eyecolor=>3},
	:@room => 1,
	:@xp => 0,
	:@level => 1,
	:@hp => 20,
	:@maxhp => 20,
	:@mp => 10,
	:@maxmp => 10,
	:@str => 5,
	:@con => 5,
	:@wis => 5,
	:@dex => 5,
	:@armor => 0,
	:@ambidexterity => 100,
	:@skin => "default",
	:@avatar => "default",
	:@spell => {},
	:@inv => {},
	:@equip => {},
	:@shortcut => [["Item 6", "Sac 1", "Armure 1", "Masque 1", "Lettre 3", "Weapon 4", "Joyaux 11", "Skill 7", "Lettre 2", "Skill 6"], ["affections", "inventory", "equipement", "who", "spells", "skills", "team", "score", "option", "aide"]],
	:@hunger => 0,
},

#Heroe 4
{
	:@id => 4,
	:@name => "Malekal",
	:@password => "37eff4bfa7d88a6e75c8804ecff8659b",
	:@authlevel => 0,
	:@desc => {:sex=>1, :height=>1, :haircolor=>2, :hairlength=>5, :eyecolor=>4},
	:@room => 2,
	:@xp => 174,
	:@level => 2,
	:@hp => 28,
	:@maxhp => 28,
	:@mp => 15,
	:@maxmp => 15,
	:@str => 5,
	:@con => 8,
	:@wis => 5,
	:@dex => 5,
	:@armor => 5,
	:@ambidexterity => 1,
	:@skin => "default",
	:@avatar => "default",
	:@spell => {},
	:@inv => {},
	:@equip => {:torse=>7, :main_gauche=>1},
	:@shortcut => [["Item 6", "Sac 1", "Armure 1", "Masque 1", "Lettre 3", "Weapon 4", "Joyaux 11", "Skill 7", "Lettre 2", "Skill 6"], ["affections", "inventory", "equipement", "who", "spells", "skills", "team", "score", "option", "aide"]],
	:@hunger => 320,
},

#Heroe 5
{
	:@id => 5,
	:@name => "Elea",
	:@password => "fee3db60d9e652d8bf728c834b0d6317",
	:@authlevel => 0,
	:@desc => {:sex=>2, :height=>2, :haircolor=>2, :hairlength=>5, :eyecolor=>1},
	:@room => 17,
	:@xp => 166,
	:@level => 2,
	:@hp => 25,
	:@maxhp => 25,
	:@mp => 18,
	:@maxmp => 18,
	:@str => 5,
	:@con => 5,
	:@wis => 8,
	:@dex => 5,
	:@armor => 5,
	:@ambidexterity => 1,
	:@skin => "default",
	:@avatar => "default",
	:@spell => {},
	:@inv => {8=>1, 10=>7, 1=>1},
	:@equip => {:main_gauche=>1, :torse=>7, :main_droite=>1},
	:@shortcut => [["Item 6", "Sac 1", "Armure 1", "Masque 1", "Lettre 3", "Weapon 4", "Joyaux 11", "Skill 7", "Lettre 2", "Skill 6"], ["affections", "inventory", "equipement", "who", "spells", "skills", "team", "score", "option", "aide"]],
	:@hunger => 1080,
},

